import 'package:eparking/models/carSlot.dart';

const DUMMY_CAR_SLOTS = const [
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
  CarSlot(slotNumber: "1", status: 0),
];
